version: '3.4'

services:
  backend: 
    image: ${CI_REGISTRY_IMAGE}:laravel-latest
    container_name: laravel_main
    restart: always
    networks:
      web_db:
      nginx:
    environment:
      DB_HOST: "mysql81"
      DB_PORT: "3306"
      DB_DATABASE: ${DATABASE}
      DB_USERNAME: "root"
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_CONNECTION: "mysql"
      APP_URL: ${APP_URL}
      DEBUG: "false"
      APP_KEY: ${APP_KEY}
      APP_NAME: "Laravel project"
    volumes: 
      - storage:/var/www/html/storage
    
volumes:
  storage: 

networks:
  nginx:
    name: nginx_web
    external: true
  web_db:
    name: databases_default
    external: true