version: '3.4'

services:

  mysql81:
    image: mysql:8.1
    ports:
      - "3306:3306"
    volumes:
      - storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "<enter high quality password>"
    restart: always


volumes:
  storage: